### ISSUE TITLE
$sails.get not called when returned as resolve for anguilar-ui-router

### ISSUE THREAD

**Issue by circuitlego** [janpantel/angular-sails#28]
If I try to use $sails in a resolve like $http is used in the [ui-router docs](https://github.com/angular-ui/ui-router/wiki):

    .state('base.main.register', {
        url: '/register',
        templateUrl: 'modules/site/register.html',
        resolve: {
            campuses: function($sails) {
                return $sails.get('/resource').
                    then(function (res) {
                        console.log(res);
                    });
            }
        }
    }

1)It never gets called and 2) **the page never finishes loading**.  If I, however, simply move the code out of the resolve and into a controller, it works great.

    .state('base.main.register', {
        url: '/register',
        templateUrl: 'modules/site/register.html',
        controller: function ($sails) {
             $sails.get('/resource').
                  then(function (res) {
                      console.log(res);
                  });
        }
    }

**Comment by TheSharpieOne** [comment]
Just looking at this again with fresh eyes... you need to return something in your `.then(function(){...})` so it can be passed to the next step/'link' in the chain.  With what you have, resolve will be getting `undefined`.

Here is a stupid quick example of this chaining http://jsfiddle.net/TheSharpieOne/8rmuqj8q/
In the console your can see what value gets passed to each of the `.then()`s  The first one gets the value that was passed, but because it doesn't return it (`return val`), the next function gets `undefined`/nothing.

In your example, `return res` at the end of the function or just get rid of the `.then()`.

**Comment by TheSharpieOne** [comment]
Closing this issue as it is not active.  Try the latest release and if you are still experiencing this issue, please re-open it.
