### ISSUE TITLE
request function error

### ISSUE THREAD

**Issue by Oldwo1f** [janpantel/angular-sails#56]
I would like to modify the headers of my socket call. For this i would like to use [sails  request method](http://sailsjs.org/#!/documentation/reference/websockets/sails.io.js/socket.request.html) : 
```
io.socket.request({
  method: 'get',
  url: '/user/3/friends',
  params: {},
  headers: {}
})
```

It seems to be implemented because when i use 
```
$sails.request({url:"/subscribeNotif",method:'GET'})

```
with no url parameter, he ask me for an url.

But the request dont fire and i got an 'undefied' on the request item.

Any idea of what is happening there?

**Comment by TheSharpieOne** [comment]
Currently `$sails` just wraps the `put`, `post`, `get`, and `delete` methods as well as `on`, `off`, and `once`.  This is just to make those common, higher-level functions play nice with angular; so that angular knows when to digest and triggers your 'callback' function.  All the rest of sails.io.js is still accessible directly on `$sails`, though you will need to manually handle triggering digest when something is returned.

In this case, you are actually calling the [sails.io.js request function](https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L840)

**Comment by Oldwo1f** [comment]
thanks for you answer. I got another question:
Is there a way to handle authentication for socket request? (set authorisations headers for JWToken connexion)

If not, maybe i can try to make a pull request to implement this request method on ng-sails.
Maybe you can provide me some help to start.

**Comment by TheSharpieOne** [comment]
Check out [2.0 branch](https://github.com/janpantel/angular-sails/tree/2.0), it should support what you need.  Eventually I will move it to master and make it an official release, but I want to add another feature to it but do not have time right now.

**Comment by Oldwo1f** [comment]
Ok thanks,
I ll look at it.

I think you can close the issue

**Comment by Oldwo1f** [comment]
Hi
I tryed out the 2.0 branch. And it did not work for me.
The request method is still undefined

**Comment by TheSharpieOne** [comment]
Sorry, I didn't clarify.  2.0 is a rewrite, it doesn't use sails.io.js.  You can just define headers in your request as you would normally do it for [`$http`](https://docs.angularjs.org/api/ng/service/$http#usage).  You can do something like `$sails.get(url, [config])`
```
$sails.get('/api/my/endpoint',{headers:{Authenicate: 'Bearer: blahblah'}}).success(function(){...}).error(function(){...})
```
And it **should** send your headers along with it.

As for the current release of angular-sails:
I also want to point out that since `request()` is not being wrapped by `$sails`, it is just exposed, when accessing the `request` through `$sails` it will not return a promise as the other end points do.  You will need to provide a callback and `$apply()` the changes yourself.
```
$sails.request({
  method: 'get',
  url: '/user/3/friends',
  params: {},
  headers: {}
}, function(responseBody, responseJwr){
  // do something...
  $scope.$apply();
})
```

**Comment by Oldwo1f** [comment]
thanks for your answer

2015-03-13 2:06 GMT+01:00 Evan Sharp <notifications@github.com>:

**Comment by TheSharpieOne** [comment]
Closing this.  If you feel that this has not been resolved, please re-open the issue.
