### ISSUE TITLE
`off` with function doesn't work

### ISSUE THREAD

**Issue by TheSharpieOne** [janpantel/angular-sails#60]
calling `off(eventName, fnCallback)` doesn't work.  This is a two part problem.  Firstm the second argument in off (`fnCallback`) is not really a callback, but the original function that you want `off`ed.  `$sails` is wrapping this function before it passes it to the socket.  
The second issue is due to the way the `on` wraps it's callback function.  essentially creating a new anonymous function that cannot be identified to be `off`ed.

Suggested fixes:
Have `on` return a function what when called removes the listener.  Similar to angular's `$on` and `$watch`.  This would remove the `off` method on `$sails`
Or
Rework the way `on` and `off` to track or map the functions passed to `on` to the wrapped functions passed to the socket.  Then when `off` is called with a function, use the function to retrieve the wrapped function and call the socket `off` with that.

**Comment by robgrimball** [comment]
Now that I am using $sails.on to create listeners for model changes so I can update my UI-Grid, I am running into this bug I suppose.  I can't seem to delete the listener in my SPA.  I would guess the first suggested fix would seem to follow what you did with modelUpdater, and it seems to follow angular's approach as well.  This isn't terribly critical for me that I be able to delete this listener since I don't actually do anything other than tell the grid to update it's view, but if milestone 2.0.0 is far off then it would certainly be nice to see it sneak it's way into the 1.x versioning.

**Comment by TheSharpieOne** [comment]
This is only an issue when using a function to identify which specific handler you want removed.  For instance, `$sails.off('user')` will work.  It will remove all of the listeners listening for the `user` event.  Its just if you want to remove a specific handler from a specific event it is not possible.

It would be relatively easy to implement the first suggestion on 1.x until 2.0.0 is finalized.
