### ISSUE TITLE
cant force reconnect

### ISSUE THREAD

**Issue by OriTheMan** [janpantel/angular-sails#72]
Hi,
im developing app using phonegap, in IOS there is issue, that if you minimize the app and using other apps, the connection to the server stops after 2 min.
when im open again the app, the socket disconnected and cant reconnect again.

how can i solve this issue and force reconnect to the socket?

**Comment by TheSharpieOne** [comment]
You can use [`$sails.connect()`](https://github.com/janpantel/angular-sails/blob/master/src/service/angular-sails.js#L84-L97) which will eventually [call sail.io.js's `_connect()` method](https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L349) which will, in the end connect with a [new socket](https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L480).
One advantage to doing it this is that it will [attempt](https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L48) to [reply](https://github.com/balderdashy/sails.io.js/blob/master/sails.io.js#L607-L6343) and thing that you did while the socket was disconnected. But you will lose any registered events, as they would have been registered with the old socket, not the new.

Another way it to access the raw socket functions and use socket.io's reconnect function directly.  You can do this with `$sails.socket._raw.io.reconnect()`.  This will not reply your events, but should be any registered events registered.
Note: Since [socket.io's client-sdie API docs](http://socket.io/docs/client-api/) are horrible and only list options and events (not methods), I am not 100% sure if it is `$sails.socket._raw.io.reconnect()` or `$sails.socket._raw.reconnect()` (without the `io.`).  I based that on [this stackoverflow answer](http://stackoverflow.com/a/24700263/1873485) which pertains to socket.io v1.0(+) which is [used by sails.io.js](https://github.com/balderdashy/sails.io.js/blob/master/dist/sails.io.js#L1-L6)

**Comment by TheSharpieOne** [comment]
Closing: Inactive.
