### ISSUE TITLE
What are the advantages of this library over the balderdashy one? (if any)

### ISSUE THREAD

**Issue by nathanmarks** [janpantel/angular-sails#73]
Hey,

I was just wondering what the advantages this has, if any, over https://github.com/balderdashy/angularSails

**Comment by TheSharpieOne** [comment]
In the current state, they are very similar.  This was built first, prior to https://github.com/balderdashy/angularSails (not that it really matters),

In the future (2.0.0 currently in beta release), they will be more different.  This project will no longer depend on sails.io.js (which has limited us before in the past) and aims to be a complete drop-in replacement to `$http` allowing one to effortlessly use `$sails` as if it was `$http` with all of the bells and whistles.  Behind-the-scenes, it will of-course use sockets instead of http requests.

You can close this ticket if this response satisfies you, or reply if you need more information or have follow-up questions.

**Comment by TheSharpieOne** [comment]
Closing: Inactive.
