### ISSUE TITLE
Not compatible with Sails 0.11.x?

### ISSUE THREAD

**Issue by heysailor** [janpantel/angular-sails#74]
Installing with sails 11.5 I get the following error:

error: Error (SAILS:HOOK:SOCKETS:PARSE_VIRTUAL_REQ):: Failed to parse incoming socket.io request.
...
'Sails v0.11.x is not compatible with the socket.io/sails.io.js client SDK version you are using (0.9.0). Please see the v0.11 migration guide on http://sailsjs.org for more information.'

**Comment by TheSharpieOne** [comment]
angular-sails [1.x] uses [sails.io.js](https://github.com/balderdashy/sails.io.js) to communicate with sails backend, it appears that the version of sail.io.js you are using is not compatible.  When you create a new sails project, it will drop a compatible version in your project for you.  If you upgrade/migrated from an older version of sails, you will need to update sail.io.js.  You can get the latest from [their repo](https://github.com/balderdashy/sails.io.js).

**Comment by heysailor** [comment]
Sorry - this was using angular-sails 2.0 beta 3, and a fresh install of
sails 11.5 and the latest socket.io-client.

**Comment by TheSharpieOne** [comment]
Yes, well with 2.x you will not need sail.io.js.  Can you inspect the connect using Chrome's devtools.  You should be able to see the information sent on the handshake easily and should look something like this: 
![image](https://cloud.githubusercontent.com/assets/664714/7995280/7c3bf6fa-0ae2-11e5-9b3b-14874c4d8c11.png)
This image is from the latest sailsjs project using angular-sails 2.0.0-beta.3

In detail, the reason why this would be happening: [Sails' socket hook](https://github.com/balderdashy/sails-hook-sockets) [looks on the querystring to find information about the socket connection](https://github.com/balderdashy/sails-hook-sockets/blob/v0.11.21/lib/parse-sdk-metadata.js#L24-L26).  If the socket doesn't provide the info.... [sails just assumes its 0.9.0](https://github.com/balderdashy/sails-hook-sockets/blob/v0.11.21/lib/parse-sdk-metadata.js#L19-L21).  Knowing this, in the v2 where we are not using sail.io.js, we had to conform to their "standard" and [implemented something to supply those values](https://github.com/janpantel/angular-sails/blob/2.0.0-beta.3/src/service/sailsSdk.js) [on the handshake](https://github.com/janpantel/angular-sails/blob/2.0/src/service/%24sailsIo.js#L39-L43).  From what it looks like, your socket connection is not sending those.  Since I cannot reproduce locally, I need more information.

**Comment by heysailor** [comment]
Apologies for late reply, I've been in a remote area for a while.

You're right, there are no sails specific values being sent with the handshake:

![screen shot 2015-06-23 at 1 36 24 pm](https://cloud.githubusercontent.com/assets/2713055/8311519/100eefbc-19ad-11e5-874c-ca4d6fb774f2.png)

Looking through the sails-angular code, the problem was that I'd set up the socket connection with the socket-io client before handing over to angular-sails. So angular-sails was using the provided socket connection rather than setting up with the expected sails values.

Would it be handy for others using angular-sails to explain you don't need to set up the socket, only include the socket.io client in the page?

Cheers for a very handy library.
